export const containers = {
  producer: 'Produção: ',
  director: 'Diretor: ',
  releaseDate: 'Data de lançamento: ',
  movies: 'filmes',
  listMoviesStarWars: 'Lista de Filmes Star Wars',
  starWars: 'Star Wars',
  starWarsInfoSite: 'Site de informações Star Wars',
  starShips: 'Naves Estelares',
  millenniumFalcon: 'Millennium Falcon',
  Movies: 'Filmes',
  characters: 'Personagens',
  darthVader: 'Darth Vader',
  vehicles: 'veículos',
  Vehicles: 'Veículos',
  atSt: 'At-ST',
  Species: 'Espécies',
  species: 'espécies',
  yoda: 'Mestre Yoda',
  Planets: 'Planetas',
  planets: 'planetas',
  name: 'Nome: ',
  eyes: 'Olhos: ',
  length: 'Tamanho: ',
  gender: 'Gênero: ',
  people: 'pessoas',
  height: 'Altura: ',
  People: 'Pessoas',
  listCharactersStarWars: 'Lista de Personagens Star Wars',
  diameter: 'Diâmetro: ',
  population: 'População: ',
  orbitalPeriod: 'Período de órbita: ',
  surfaceWater: 'Água na superfície: ',
  rotationPeriod: 'Período de rotação: ',
  averageLifeSpan: 'Tempo médio de vida: ',
  cm: 'cm',
  listSpeciesStarWars: 'Lista de espécies Star Wars',
  costInCredits: 'Custo em créditos: ',
  maxAtmosphericSpeed: 'Velocidade máxima na atmosfera: ',
  passengers: 'Passageiros: ',
  shipLength: 'Tamanho da Nave: ',
  listShipsStarWars: 'Lista de naves espaciais Star Wars',
  listPlanetsStarWars: 'Lista de Planetas Star Wars',
  speed: 'Velocidade: ',
  coruscant: 'Coruscant',
  listVehiclesStarWars: "Lista de veículos Star Wars",
}  