interface Images {
  images: {
    [index: string]: string;
  }
}

export const images: Images = {
  "images": {
    "A New Hope": './img/films/new-hope.jpg',
    "The Empire Strikes Back": './img/films/empire-strikes.jpg',
    "Return of the Jedi": './img/films/return-jedi.jpg',
    "The Phantom Menace": './img/films/phantom-manace.jpg',
    "Attack of the Clones": './img/films/attack-clones.png',
    "Revenge of the Sith": './img/films/revenge-sith.jpg',
    'Luke Skywalker': './img/persons/luke.jpg',
    'C-3PO': './img/persons/c3po.jpg',
    'R2-D2': './img/persons/r2d2.jpg',
    'Darth Vader': './img/persons/darth-vader.jpg',
    'Leia Organa': './img/persons/leia.jpg',
    'Owen Lars': './img/persons/owen-lars.jpg',
    'Beru Whitesun lars': './img/persons/beru.jpg',
    'R5-D4': './img/persons/r5d4.jpg',
    'Biggs Darklighter': './img/persons/biggs-darklighter.jpg',
    'Obi-Wan Kenobi': './img/persons/obi-wan.jpg',
    "Coruscant": './img/planets/coruscant.jpg',
    "Tatooine": './img/planets/tatooine.jpg',
    "Alderaan": './img/planets/alderaan.jpg',
    "Yavin IV": './img/planets/yavinIV.jpg',
    "Hoth": './img/planets/hoth.jpg',
    "Dagobah": './img/planets/dagobah.jpg',
    "Bespin": './img/planets/bespin.jpg',
    "Endor": './img/planets/endor.jpg',
    "Naboo": './img/planets/naboo.jpg',
    "Kamino": './img/planets/kamino.jpg',
    "CR90 corvette": './img/ships/cr90.jpg',
    "Star Destroyer": './img/ships/star-destroyed.jpg',
    "Sentinel-class landing craft": './img/ships/sentinel-class.jpg',
    "Death Star": './img/ships/death-star.jpg',
    "Millennium Falcon": './img/ships/millennium-falcon.jpg',
    "Y-wing": './img/ships/y-wing.jpg',
    "X-wing": './img/ships/x-wing.jpg',
    "TIE Advanced x1": './img/ships/tie-advanced.jpg',
    "Executor": './img/ships/executor.jpg',
    "Rebel transport": './img/ships/rebel-transport.jpg',
    "Human": './img/persons/luke.jpg',
    "Droid": './img/persons/c3po.jpg',
    "Wookie": './img/species/wookie.jpg',
    "Rodian": './img/species/rodian.jpg',
    "Yoda's species": './img/persons/yoda.jpg',
    "Hutt": './img/species/hutt.jpg',
    "Trandoshan": './img/species/trandoshan.jpg',
    "Mon Calamari": './img/species/mon-calamari.jpg',
    "Ewok": './img/species/ewok.jpg',
    "Sullustan": './img/species/sullustan.jpg',
    "AT-AT": './img/vehicles/at-at.jpg',
    "AT-ST": './img/vehicles/at-st.jpg',
    "Sand Crawler": './img/vehicles/sand-crawler.jpg',
    "T-16 skyhopper": './img/vehicles/t16-skyhooper.jpg',
    "X-34 landspeeder": './img/vehicles/x34-landspeeder.jpg',
    "TIE/LN starfighter": './img/vehicles/tie-ln-starfighter.jpg',
    "Snowspeeder": './img/vehicles/snowspeeder.jpg',
    "TIE bomber": './img/vehicles/tie-bomber.jpg',
    "Storm IV Twin-Pod cloud car": './img/vehicles/storm-IV.jpg',
    "Sail barge": './img/vehicles/sail-barger.jpg',
  }
}